name = "HiddenMarkovModelReaders"
uuid = "760a73f4-dca7-4de8-943d-18a66a2ce654"
repo = "https://github.com/DanielRivasMD/HiddenMarkovModelReaders.jl"
keywords = ["signal-processing", "unsupervised-learning", "hidden-markov-model"]
license = "MIT"
desc = " Hidden Markov model and unsupervised hypothesis generator for signal processing and anomaly detection."
authors = ["Daniel Rivas <danielrivasmd@gmail.com> and Manfred Grabherr <manfredgrabherr@gmail.com>"]
version = "0.3.0"

[deps]
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
DocumenterTools = "35a29f4d-8980-5a13-9543-d66fff28ecb8"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
StructArrays = "09ab397b-f2b6-538f-b94a-2f83cf4a842a"

[compat]
Documenter = "0.19.0 - 0.27.12"
DocumenterTools = "0.1.13"
Parameters = "0.12"
StructArrays = "0.5, 0.6"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
