name = "HiddenMarkovModelReaders"
uuid = "760a73f4-dca7-4de8-943d-18a66a2ce654"
authors = ["DanielRivasMD <danielrivasmd@gmail.com> and contributors"]
version = "0.1.0"

[deps]
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
StructArrays = "09ab397b-f2b6-538f-b94a-2f83cf4a842a"

[compat]
Parameters = "0.12"
StructArrays = "0.5, 0.6"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
